---
os: 
  - osx
osx_image: 
  - xcode10.1

#before_install:
  # Make sure composer is up-to-date
  #- composer self-update
  # Get netstat
  #- sudo apt-get update -qq
  #- sudo apt-get install net-tools

install:
  - brew tap aerickson/clamp
  # install coreutils for testing, but unlink so we have to explicitly use it
  - brew upgrade coreutils
  - brew unlink coreutils

#before_script:

script:
  # install (also tests by running 'clamp -h')
  - brew install --HEAD clamp
  # display the version installed
  - brew info clamp | grep '/usr/local/Cellar'
  # write config
  - clamp config write
  # TODO: more complicated test

